version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db  # Importante: cambiamos localhost por db
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_DATABASE=prueba-Mederi
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "prueba-Mederi"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: